---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msg-gateway-deployment
spec:
  selector:
    matchLabels:
      app: msg-gateway 
  replicas: 3
  template:
    metadata:
      labels:
        app: msg-gateway
    spec:
      containers:
      - name: msg-gateway
        image: truongpx396/openim-dev-msg_gateway:b24dd770-32
        command: ["./open_im_msg_gateway"]
        args: ["--port", "10140", "--ws_port", "10001", "--prometheus_port", "20240"]
        imagePullPolicy: Always
        ports:
        - name: rpc-port
          containerPort: 10140
        - name: ws-port
          containerPort: 10001
        - name: mgw-prome-port
          containerPort: 20240
        # readinessProbe:
        #   tcpSocket:
        #     port: 10001
        #   exec:
        #     command: ["/bin/grpc_health_probe", "-addr=:10140"]
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   tcpSocket:
        #     port: 10001
        #   exec:
        #     command: ["/bin/grpc_health_probe", "-addr=:10140"]
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        volumeMounts:
          - name: config
            mountPath: /Open-IM-Server/config
            readOnly: true
        env:
          - name: CONFIG_NAME
            value: "/Open-IM-Server"
        resources:
          requests:
            memory: "512Mi"
            cpu: 300m
          limits:
            memory: "1024Mi"
            cpu: 600m
      volumes:
        - name: config
          projected:
            sources:
            - configMap:
                name: openim-config
            - configMap:
                name: openim-notification-config
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - msg-gateway
              topologyKey: kubernetes.io/hostname
  strategy: 
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  name: msg-gateway
spec:
  ports:
    - name: msg-gateway-svc-port
      protocol: TCP
      port: 10001
      targetPort: ws-port
    - name: msg-gateway-rpc-svc-port
      protocol: TCP
      port: 10140
      targetPort: rpc-port
  selector:
    app: msg-gateway
  type: ClusterIP   

    