---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-api-chat-deployment
spec:
  selector:
    matchLabels:
      app: management-api-chat
  replicas: 3 
  template:
    metadata:
      labels:
        app: management-api-chat 
    spec:
      containers:
      - name: management-api-chat
        image: truongpx396/openim-dev-api:355074f8-59
        imagePullPolicy: Always
        ports:
        - containerPort: 10002
          name: api-port
        volumeMounts:
          - name: config
            mountPath: /openim/config
            readOnly: true
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 10002
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 10002
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        env:
          - name: CONFIG_NAME
            value: "/Open-IM-Server"
        resources:
          requests:
            memory: "100Mi"
            cpu: 70m
            # memory: "512Mi"
            # cpu: 300m
          limits:
            memory: "250Mi"
            cpu: 100m
            # memory: "1024Mi"
            # cpu: 600m
      volumes:
        - name: config
          projected:
            sources:
            - configMap:
                name: config
            - configMap:
                name: notification
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - api
              topologyKey: kubernetes.io/hostname
  strategy: 
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - name: api-svc-port
      protocol: TCP
      port: 10002
      targetPort: api-port
  selector:
    app: api
  type: ClusterIP  